export const POST_MEME_REQUEST = "POST_MEME_REQUEST";
export const POST_MEME_SUCCESS = "POST_MEME_SUCCESS";
export const POST_MEME_FAIL = "POST_MEME_FAIL";

export const GET_MEMES_REQUEST = "GET_MEMES_REQUEST";
export const GET_MEMES_SUCCESS = "GET_MEMES_SUCCESS";
export const GET_MEMES_FAIL = "GET_MEMES_FAIL";

export const GET_EXPLORE_MEMES_REQUEST = "GET_EXPLORE_MEMES_REQUEST";
export const GET_EXPLORE_MEMES_SUCCESS = "GET_EXPLORE_MEMES_SUCCESS";
export const GET_EXPLORE_MEMES_FAIL = "GET_EXPLORE_MEMES_FAIL";

export const DELETE_MEME_REQUEST = "DELETE_MEME_REQUEST";
export const DELETE_MEME_SUCCESS = "DELETE_MEME_SUCCESS";
export const DELETE_MEME_FAIL = "DELETE_MEME_FAIL";
